# Generated by Django 6.0.6 on 2026-09-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Portfolio', max_length=80)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site branding',
                'verbose_name_plural': 'Site branding',
            },
        ),
    ]
