# Generated by Django 6.0.6 on 2026-09-12 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_void', models.CharField(default='#0d1117', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #58a6ff.', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_panel', models.CharField(default='#161b22', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #58a6ff.', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_panel_edge', models.CharField(default='#30363d', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #58a6ff.', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_neon_blue', models.CharField(default='#58a6ff', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #58a6ff.', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_neon_indigo', models.CharField(default='#388bfd', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #58a6ff.', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_accent', models.CharField(default='#238636', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #58a6ff.', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_status_green', models.CharField(default='#3fb950', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #58a6ff.', regex='^#[0-9a-fA-F]{6}$')])),
                ('color_status_red', models.CharField(default='#f85149', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a hex color like #58a6ff.', regex='^#[0-9a-fA-F]{6}$')])),
                ('font_display', models.CharField(choices=[('Inter', 'Inter'), ('Poppins', 'Poppins'), ('Space Grotesk', 'Space Grotesk'), ('Manrope', 'Manrope'), ('Sora', 'Sora')], default='Inter', max_length=40)),
                ('font_mono', models.CharField(choices=[('JetBrains Mono', 'JetBrains Mono'), ('Fira Code', 'Fira Code'), ('IBM Plex Mono', 'IBM Plex Mono'), ('Roboto Mono', 'Roboto Mono')], default='JetBrains Mono', max_length=40)),
                ('radius_scale', models.CharField(choices=[('sharp', 'Sharp'), ('soft', 'Soft'), ('rounded', 'Rounded')], default='soft', max_length=10)),
                ('shadow_intensity', models.CharField(choices=[('none', 'None'), ('subtle', 'Subtle'), ('elevated', 'Elevated')], default='none', max_length=10)),
                ('button_style', models.CharField(choices=[('solid', 'Solid fill'), ('outline', 'Outline'), ('soft', 'Soft tint')], default='solid', max_length=10)),
                ('card_style', models.CharField(choices=[('clean', 'Clean border'), ('accent', 'Accent border')], default='clean', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site theme',
                'verbose_name_plural': 'Site theme',
            },
        ),
    ]
