# Generated by Django 6.0.6 on 2026-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255)),
                ('referrer', models.CharField(blank=True, max_length=255)),
                ('is_blog_post', models.BooleanField(default=False)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('session_key', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='analytics_p_created_4c2b45_idx'), models.Index(fields=['path'], name='analytics_p_path_3382b5_idx')],
            },
        ),
    ]
