# Generated by Django 6.0.8 on 2026-09-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='is_blog_post',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='slug',
        ),
    ]
