# Generated by Django 6.0.8 on 2026-09-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(help_text="Rich text (HTML), written with the admin panel's WYSIWYG editor."),
        ),
    ]
